[package]
name = "apple-secure-enclave-bindings"
version = "0.1.0"
edition = "2021"
publish = []

build = "build.rs"

[build-dependencies]
swift-bridge-build = "0.1.55"

[dependencies]
swift-bridge = "0.1.55"

[lib]
crate-type=["staticlib", "rlib"]

